lib/express_validator.js

Replace req.param call to remove deprecation msg

---

lib/express_validator.js
package.json

I just mirrored the same output that was returned from the other check* methods. Fixes #113 
Also bumped the patch number. @ctavan - This should be deployed to npm after this is merged in.

Fix checkHeader so that it works with optional()

---

.editorconfig
.jshintrc
.travis.yml
README.md
lib/express_validator.js
package.json

- Add jshint
- Add editorconfig
- Add node 0.12 to travis.yml
- Remove dead gist link
- Add license to package.json
- Add changelog script
- Bump validator to 3.39.0
Closes https://github.com/ctavan/express-validator/issues/129
Closes #136

Config changes/other cleanup

---

README.md
lib/express_validator.js
test/customSanitizersTest.js
test/helpers/app.js

Hi
In my project I needed the ability to add custom santizers. For example you have normalizeEmail but I need normalizePhone. So i did it. Now you can in options add customSantizers, it is very similar to customValidators (it is refactored customValidators). I have not found tests for customValidators, so I did not make tests for this method.

added custom santizers

---

lib/express_validator.js

Provide a default options value

---

.gitignore
.jscsrc
.travis.yml
lib/express_validator.js
package.json
test/helpers/app.js
test/mappedOutputTest.js
test/nestedInputTest.js
test/optionalTest.js
test/regexRouteTest.js
test/sanitizeBodyTest.js

Add jscsrc, add jscs/jshint to travis build, and fix errors thrown by JSHint/JSCS.

---

package.json

Updated validator from 3.40.1 to 4.0.2.

Updated to the latest validator version (4.0.2)

---

README.md

Added a badge to reflect the dependency status. Maybe it encourages people to file pull requests for outdated dependencies :)

Added badge reflecting the dependency status

---

README.md

Add details about implementation of async validation.

Asynchronous validation implementation

---

package.json

The company I work for doesn't like packages with outdated dependencies, but I'd hate to loose this package.

Update production depedencies

---

package.json

Many locals have been added.
[Changelog](https://github.com/chriso/validator.js/blob/master/CHANGELOG.md) | [Commit summery](https://github.com/chriso/validator.js/compare/5.4.0...5.6.0)

Validator.js version bump

---

package.json
test/regexRouteTest.js

Validator v6

---

lib/express_validator.js

As suggested by @srkimir, this PR should fix #222.

Bug Fix: Optional validate method may not be applied when using a schema

---

index.d.ts

Allow to use fully custom error formatter without typescript error.

Update TypeScript definitions

---

README.md

fix markdown title syntax in README.md

---

index.d.ts

This has been a bad day. This is tested both in project tests and in
real project and should resolve the issues with imports in TypeScript.
Fixes: #350

REF #350 Fix for TypeScript Typings Revisted

---

.editorconfig
README.md
UPGRADE_GUIDE.md

This completes the version 4 milestone by adding a reasonable README file with lots of details about our APIs.

Version 4 -  Docs

---

README.md
check/index.d.ts
check/index.js
check/schema.d.ts
check/schema.js
check/schema.spec.js
check/schema.spec.ts
lib/chain-creator.js
lib/custom-methods.js
lib/express_validator.js

check: schema to chain mapper

---

README.md
check/check.js
check/check.spec.js
check/check.spec.ts
filter/sanitize.d.ts
filter/sanitize.js
filter/sanitize.spec.js
filter/sanitize.spec.ts
utils/select-fields.js
utils/select-fields.spec.js

Custom Sanitizer

---

check/one-of.js
filter/matched-data.js
filter/matched-data.spec.js

Fix matchedData use with oneOf

---

check/one-of.js
filter/matched-data.js
filter/matched-data.spec.js

`matchedData` would
- not work at all with multiple `oneOf` calls;
- not pick values from subchains that succeeded,
if the value failed in another subchain.
Closes #536
Fixes #533

filter: fix matchedData interop with oneOf

---

check/schema.js

fix "exists" can not custom message when using schema validation.

fix "exists" can not customize message when using schema validation

---

docs/api-validation-chain.md

Hello.
I noticed that docs render weird characters on npm, check it out [here](https://www.npmjs.com/package/express-validator#customvalidator).
This PR should fix it making it look normal.

Remove weird characters from docs/api-validation-chain.md

---

declarations/validator.d.ts
docs/api-sanitization-chain.md
src/chain/sanitizers-impl.spec.ts
src/chain/sanitizers-impl.ts
src/chain/sanitizers.ts

This pull request adds a toArray() sanitizer as discussed in #679.

Add toArray() sanitizer (#679)

---

declarations/validator.d.ts
package-lock.json
package.json
src/chain/validators-impl.ts
src/chain/validators.ts

https://github.com/chriso/validator.js/blob/11.0.0/CHANGELOG.md
Most of the LOC added because Prettier reformatted the file 🙃

Validator 11

---

src/chain/context-handler-impl.spec.ts
src/chain/context-handler-impl.ts
src/chain/context-handler.ts
src/chain/context-runner-impl.spec.ts
src/chain/context-runner-impl.ts
src/chain/context-runner.ts
src/chain/sanitization-chain.ts
src/chain/sanitizers-impl.spec.ts
src/chain/sanitizers-impl.ts
src/chain/validation-chain.ts
src/chain/validators-impl.spec.ts
src/chain/validators-impl.ts
src/chain/validators.ts
src/context-builder.spec.ts
src/context-builder.ts
src/context-items/custom-validation.spec.ts
src/context-items/sanitization.spec.ts
src/context-items/standard-validation.spec.ts
src/context.spec.ts
src/context.ts
src/middlewares/check.spec.ts
src/middlewares/check.ts
src/middlewares/one-of.spec.ts
src/middlewares/one-of.ts
src/middlewares/sanitize.spec.ts
src/middlewares/sanitize.ts
src/middlewares/schema.spec.ts
src/middlewares/schema.ts
src/middlewares/validation-chain-builders.spec.ts
src/validation-result.spec.ts

Implement a `ContextBuilder` class which helps building `Context`s which will then be internally used by the current middlewares.

Context Builder

---

docs/api-validation-chain.md
src/chain/validators-impl.spec.ts
src/chain/validators-impl.ts
src/chain/validators.ts

Added two options (min and max, like in isLength()) to validate the length of an array.
```javascript
body('array')
.isArray({min: 3, max: 6})
```

added options to validate array length in isArray()

---

package-lock.json
package.json
src/validation-result.ts

Prettier seem to have got a breaking change, what is unfortunate 😞 
On the plus side, tons of sub-dependencies were removed!

Upgrade a few packages

---

declarations/validator.d.ts
package-lock.json
package.json
src/chain/validators-impl.ts

Adding new methods from validator 13 and upgrading validator 13.
Test coverage is 100%

Bumping ValidatorJs version to 13.0.0

---

src/chain/context-runner-impl.spec.ts
src/chain/context-runner-impl.ts
src/chain/context-runner.ts
src/context-items/chain-condition.spec.ts
src/context-items/chain-condition.ts
src/context-items/sanitization.spec.ts
src/context-items/sanitization.ts
src/middlewares/one-of.spec.ts
src/middlewares/one-of.ts

Don't modify requests if oneOf chain didn't succeed

---

docs/index.md

Without a fix, this server will validate a request that includes valid values transmitted via another vector (e.g. query string) but only use parameters from the request body. `check` will reject an invalid value for a parameter found on the body, but not an empty value. This is a bug, and repeating this mistake may create security vulnerabilities if programmers expect `req.body` to contain the parameters described by the array of validation middlewares preceding the request handler.
Example program using Getting Started code verbatim:
```javascript
const PORT = Number(process.env.PORT) || 8123
const User = {
create(params) {
console.log('mock: User.create called with', params)
return Promise.resolve(params)
}
}
const express = require('express');
const app = express(); …
```

Fix bug in Getting Started section

---

package-lock.json
package.json

upgrade due to security concern. https://github.com/express-validator/express-validator/issues/901

upgrade lodash and types/lodash

---

docs/api-sanitization-chain.md
src/chain/sanitizers-impl.spec.ts
src/chain/sanitizers-impl.ts
src/chain/sanitizers.ts

related issue https://github.com/express-validator/express-validator/issues/581

Add toLowerCase and toUpperCase methods to sanitizers

---

docs/api-sanitization-chain.md
src/chain/sanitizers-impl.spec.ts
src/chain/sanitizers-impl.ts
src/chain/sanitizers.ts

This PR adds the 'default' sanitizer.
See more in #929.
This closes #929 and closes #856

Add 'default' sanitizer

---

docs/index.md

Fixes #940. Document updating without tests.

docs: update recommended node version

---

website/siteConfig.js

Closed #735. See https://docusaurus.io/docs/en/site-config#deleteddocs-object.

docs: totally hide deleted docs

---

docs/api-sanitization-chain.md
src/chain/sanitizers-impl.spec.ts
src/chain/sanitizers-impl.ts
src/chain/sanitizers.ts

This PR adds 'replace' sanitizer.
See more in the linked issue.
This closes #924

Add 'replace' sanitizer

---

declarations/validator.d.ts
package-lock.json
package.json
src/chain/validators-impl.ts
src/chain/validators.ts
src/options.ts

Update `validator` to 13.5.0
This allows to implement new validators and to add support to more locales.

chore(deps): bump validator to 13.5.1

---

docs/feature-error-messages.md

docs(feature-error-messages): add 'Complex errors' section

---

src/middlewares/validation-chain-builders.spec.ts

test: fix typo

---

src/chain/validators-impl.spec.ts
src/chain/validators-impl.ts
src/chain/validators.ts
src/options.ts

feat(isBoolean): implement 'strict' option

---

README.md
docs/api-sanitization-chain.md
docs/api-validation-chain.md
docs/faq.md
docs/feature-custom-validators-sanitizers.md
docs/feature-sanitization.md
docs/index.md
website/i18n/en.json
website/sidebars.json

#931, #883 and #791 
Changes: 
- New FAQ page
- Warning about not using `notEmpty()` for arrays
- New notice about Standard validators/sanitizers type conversion to string.
- Explanation of how to properly validate/sanitize all array values
- Update validator.js repo URL

docs: improve docs

---

src/options.ts

fix(isURL): accept non-default strings for protocols option

---

docs/api-validation-result.md
docs/feature-custom-validators-sanitizers.md
docs/feature-running-imperatively.md
docs/feature-wildcards.md
docs/index.md

Co-Authored-By: islasjuanp <islasjuanp@users.noreply.github.com>
References https://github.com/express-validator/express-validator/pull/788#pullrequestreview-575447360
Closes #759

docs: add TS examples

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Improve default labels of issue templates

chore: update issue templates

---

src/chain/validators-impl.ts
src/chain/validators.ts
src/options.ts

Added options support to isAlphanumeric, closes #1026

Added options support to isAlphanumeric

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: update `bug_report.md`

---

declarations/validator.d.ts
package-lock.json
package.json
src/chain/validators-impl.ts
src/chain/validators.ts
src/options.ts

feat: bump validator to 13.6.0

---

src/middlewares/schema.spec.ts
src/middlewares/schema.ts
src/validation-result.ts

fix(`checkSchema`): correctly allow falsy values as options

---

.eslintrc
package-lock.json
package.json
src/chain/context-runner-impl.spec.ts

Repeat of #983, but for the master branch.
There was a breaking change in eslint-config-prettier:
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

Upgrade TS + lint deps

---

declarations/validator.d.ts
package-lock.json
package.json
src/chain/sanitizers-impl.spec.ts
src/chain/validators-impl.ts
src/chain/validators.ts
src/options.ts

feat: update to support validator 13.9.0

---

docs/api/validation-chain.md
website/versioned_docs/version-7.0.0/api/validation-chain.md

https://github.com/express-validator/express-validator/issues/1239

Deleted the Extra Closing Parenthesis in validation-chain.md

---

docs/api/validation-result.md
website/versioned_docs/version-7.0.0/api/validation-result.md

Fixed typo, changed `thefore` to `therefore`

docs: update validation result

---

docs/api/check-schema.md
website/versioned_docs/version-7.0.0/api/check-schema.md

Correct a typo that appears twice in the checkSchema doc.

docs: fix typo

---

docs/api/misc.md
src/context-items/custom-validation.ts
src/context-items/sanitization.ts
website/versioned_docs/version-5.2.0/api-validation-chain.md
website/versioned_docs/version-5.2.0/feature-error-messages.md
website/versioned_docs/version-5.3.0/api-validation-chain.md
website/versioned_docs/version-5.3.0/feature-error-messages.md
website/versioned_docs/version-6.0.0/api-validation-chain.md
website/versioned_docs/version-6.1.0/api-validation-chain.md
website/versioned_docs/version-7.0.0/api/misc.md
website/versioned_docs/version-7.2.0/api/misc.md

chore: fix typos

---

src/middlewares/exact.ts

refactor: remove unnecessary assertion

---

src/context-items/custom-validation.ts
src/validation-result.ts

use optional chain for better readability

refactor: use optional chain
