CHANGELOG.md, README.md
The changelog for this repo was very outdated, so I updated all of the tags and used [github-changes](https://github.com/lalitkapoor/github-changes) to generate a CHANGELOG.md from the commits. A list of commit messages may not be the most ideal format for a change log, but it gets us updated quickly.
I used the following command to generate the file:
`github-changes -o ctavan -r express-validator -a -m YYYY/MM/DD --no-merges`
=> Move change log into its own file and expand it using github-changes.

lib/express_validator.js, package.json, test/sanitizerTest.js
When sanitizing, it was ignoring '', false, and 0. Changed to only ignore null and undefined. Should fix #148.
=> Test for falsy values in sanitization.

README.md, lib/express_validator.js, test/withMessageTest.js
Currently, when validations are chained, only a single message to be used for all errors in the chain can be provided. This PR adds a method `.withMessage(message)`, to be called immediately after the validation in the chain, that provides the new message via the errorFormatter. 
In this example:
```javascript
req.check('param', 'Default Message')
.notEmpty()
.isInt().withMessage('Custom message')
```
if 'param' is empty, the message 'Default Message' will be used, but if it is provided and is not an integer, 'Custom Message' will be used instead. 
The implementation is simple enough - just track the param & value of the last error generated and then when `withMessage` is called, pop the last error and re-generate it with the new message. 
Tests provided, any feedback welcome.
=> #126 - Added withMessage method to provide a message per validation

lib/express_validator.js, test/withMessageTest.js
Currently, if in a chained validation one validation fails, and no withMessage is provided, but all further validations pass and a with message is provided, the original error will be given the custom message incorrectly. 
This PR fixes this issue, by ensuring that if a validation passes no calls to withMessage further down the chain will attempt to update the error message. 
Test included, feedback welcome.
=> Fixed bug where custom messages would be applied incorrectly

README.md, lib/express_validator.js, test/checkBodySchemaTest.js, test/checkParamsSchemaTest.js, test/checkQuerySchemaTest.js, test/optionalSchemaTest.js
I've added the functionality to be able to validate by passing an object schema to check, checkBody etc. as an alternative to chaining.
example:
````javascript
req.checkBody({
'email': {
notEmpty: true,
isEmail:
failMsg: 'Invalid Email'
}
},
'password': {
notEmpty: true
},
'name.first': {
notEmpty: true,
isLength: {
options: [2, 10],
failMsg: 'Must be between 2 and 10 chars long'
}
}
});
````
passing true will use the default error message.
=> Add validation by schema

README.md, lib/express_validator.js, package.json, test/asyncTest.js, test/helpers/app.js
Adds the functionality to be able to return a promise from a custom validator.
Requires that `req.asyncValidationErrors()` is used which will return a promise, rather than `req.validationErrors()` otherwise async validators may not have completed. I added a console warning if you use an async validator and then use `validationErrors`, as it could be a common mistake...
`asyncValidationErrors` will resolve if there are no errors and will reject with any (a)synchronous validation errors!
=> Async Validation

lib/express_validator.js, test/formatParamOutputTest.js, test/nestedInputTest.js, test/optionalSchemaTest.js, test/sanitizerResultTest.js
This is a fix for https://github.com/ctavan/express-validator/issues/165.
I wrapped `errorFormatter()` in a function called `formatParamOutput` that formats the param for output. Also exported this function so that I could easily test it. In the future we could possibly add other functions to the utils object for testing.
Would appreciate a code review by @chrissinclair or @Jakeii. Just leave a comment if you've finished reviewing or have any feedback.
=> Fix the output of nested params in error object.

.travis.yml, README.md, lib/express_validator.js, package.json, test/optionalSchemaTest.js, test/optionalTest.js, test/sanitizeHeadersTest.js
- Added options arguments to `optional()` to allow for checking for falsy values. (fix #120)
- Added docs for sanitizer arguments (fix #182)
- Added `sanitizeHeaders()` with tests and docs. (fix #177)
- Update validator to 4.2.x
- Added Node v4.0 and v4.1 to Travis.
@ctavan ... Thoughts? I attempted to add that feature to `optional()` while still being backwards-compatible.
=> Optional() options, sanitizeHeaders(), and documentation

README.md, lib/express_validator.js, package.json, test/withMessageTest.js
Minor change in API, backwards compatibility maintained:
- isLenght({ min: 2, max: 10 })
- isByteLenght({ min: 2, max: 10 })
- isLenght({ min: 4 })
- isByteLenght({ max: 8 })
closes #196
NOTE: This PR includes changes to README which illustrate an api which changed, so a new version should be released after merging. Backwards compatibility was maintained so a minor version bump should suffice.
=> Upgrade dependency (validator.js) from 4.2.x -> 4.5.x

lib/express_validator.js, package.json
The _.contains alias was dropped in 4.0.0 in favor of _.includes
This change is compatible with 3.10.x. All the other lodash stuff should be good to go for 4.0.0
=> Change lodash method names to match 4.x changes

lib/express_validator.js, package.json
If I understood the functionality of reflect correctly, this should be the fix needed for the upgrade. It's a bit unfortunate that they took down the documentation for `.settle()` so that I cannot really look the semantics up.
=> Upgraded bluebird

lib/express_validator.js, test/helpers/app.js
Based on http://bluebirdjs.com/docs/api/reflect.html#comment-2369616577, should fix #220.
=> Convert promises to Bluebird promises in order to use reflect(). 

lib/express_validator.js, package.json
Added lines from @Jakeii's suggestion in https://github.com/ctavan/express-validator/pull/229, so that all tests pass with an upgrade to node-validator v5.
=> Update node-validator to v5 and restore automatic string coercion.

lib/express_validator.js
Please check open issue https://github.com/ctavan/express-validator/issues/242 for example and details.
Changes from PR will not `delete` param error message from schema, it will skip validation if `methodName` is equal to `errorMessage`. On this way same predefined schema in application can be reused safely.
=> avoid deletion of param error message when using schema validation

lib/express_validator.js, test/checkOptionalSchemaTest.js
Fixes issue with: https://github.com/ctavan/express-validator/issues/259
BUG: If a schema with `optional: true` is passed to `req.check` and the optional parameter is omitted from the request, then the `locate` function will return `undefined` for that parameter and all subsequent validations will not run.
=> Fixes optional params breaking req.check

README.md, lib/express_validator.js, test/formatErrorTest.js
In prior versions of express-validator, you could include tokens like
%0, %1, etc in error message, and validator.js would replace them with
the value of the input or parameters passed to the validators.
This commit restores that behavior.
%0 is the value of the parameter being tested
%1... are the values of the parameters passed to the validator function
itself.
=> String formatting for error messages

README.md, lib/express_validator.js, test/optionalSchemaTest.js
To facilitate:
optional: {
options: { checkFalsy: true }
},
as an alias of
optional: {
options: [{ checkFalsy: true }]
},
=> Options in schema validation don't have to be an array

README.md, lib/express_validator.js, test/getValidationErrorsTest.js
As mentioned in issue #249 the API for retrieving validation errors is rather cumbersome. 
To solve this problem I've introduced a new `req.getValidationErrors()` method which is async by default and returns errors as part of the promise resolution. This makes it easier to write readable code, especially when coupled with generators, and keeps code consistent when switching between sync/async.
For example, using generators with the new method code is now written as such:
```javascript
var errors = yield req.getValidationErrors();
if (errors) {
res.send('There were errors');
} else {
res.send('All is well');
}
```
=> Introducing friendlier API for retrieving validation errors

.jshintrc, README.md, lib/express_validator.js, lib/utils.js, test/decorateAsValidationResultTest.js, test/getValidationErrorsTest.js
Instead of returning the errors directly, the new method `#getValidationResult()` (previously `#getValidationErrors()`, see #269) will return a
result object which can be used to retrieve the errors in different ways.
- `#all()`: returns all errors
- `#mapped()`: returns a mapped version of the errors
- `#useFirstErrorOnly()`: determines that `#all()`/`#mapped()` will work with only the first error occurrence for each param
- `#throw()`: throws an `Error` with the same API as the result object
Tasks:
Closes #235, closes #223, closes #30 
---
**Bonus:** I reorganized lots of stuff in the docs!
=> #getValidationResult() validation result object

package.json
This is a fix for [`fd2631f`](https://github.com/ctavan/express-validator/commit/fd2631f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40); Those dependencies are required by the library's type definitions.
@gustavohenke, must have [missed](https://github.com/ctavan/express-validator/pull/289/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35) them when you squashed that PR :)
=> Moved necessary dependencies back to `dependencies`

lib/express_validator.js, test/testabilityTest.js
Hello!
At the company I work for called INgrooves, we use `express-validator` in several applications — we thank all contributors of this project for an excellent tool!
Recently, we uncovered a bug in express-validator, which this PR fixes.
- each of our apps used express-validator and some `customValidators`
- we merged a few of these apps together into a single app, and experienced breakage — because `express-validator` keeps its `customValidators` in module-level state — the custom validators for route B overwrite the custom validators for route A, etc
This PR fixes the problem by simply moving this global state within the express validator constructor's scope
- thus now each call to express validator has its own private ValidationChain prototype to work with (also internalized …
=> Reduce module state to improve testability

index.d.ts, test/typeDefinitionTest.ts
trim, ltrim, and rtrim should be usable without parameter using typescript.
=> declare trim parameter as optional in type definitions

package.json
Update `@types/bluebird` to match version of `bluebird`
```
"dependencies": {
"@types/bluebird": "^3.4.0",
"bluebird": "^3.4.0",
}
```
=> Update @types/bluebird package. Closes #357

lib/express_validator.js, test/validatorReturnTest.js
I wanted to use the `isUUID` validator. I've set the version as option, like so:
```js
isUUID: {
options: {
version: 4
}
}
```
it turned out, that validator expects the version as a second param instead:
https://github.com/chriso/validator.js/blob/master/lib/isUUID.js#L26
so the version was `{version: 4}` and the line
```js
var version = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 'all';
```
didn't fall back to `all` correctly. Now when it tried to find the pattern, it got undefined:
```js
var pattern = uuid[version]; // uuid[{version: 4}] does not exist
return pattern && pattern.test(str);
```
this lib then threw error as it did `undefined.then` [here](https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L494).
This PR fixes such …
=> Fix `isValid.then` check bug in case validator returns undefined/null

README.md
While working with this library, confusion was created by the link title which incorrectly reads 'node-validator', which is not only incorrect, but the link does not take you there.
I know it's petty, but it will hopefully save others time or confusion in the future.
Thanks for the efforts in this library.
=> Innaccurate dependency claim

check/select-fields.js, check/select-fields.spec.js, lib/express_validator.js, lib/utils.js, test/check.spec.js
Follow-up of #383.
Adds support for wildcard field selection, such as `foo.*.bar` (translates to "every `bar` below a key below `foo`").
There's NO supoprt for deep wildcard searching at this moment, eg `foo.**` (which translates to "everything below `foo`")
=> Version 4 - Wildcard field selection

check/index.d.ts, check/index.js, check/one-of.js, check/one-of.spec.js, check/type-definition.spec.ts
This is a follow-up of #383.
Creates another middleware function `oneOf`, that will succeed if at least one of the validator chains succeeded.
```js
const { oneOf, check } = require('express-validator/check');
app.post('/', oneOf([
check('username').isEmail(),
check('password').isLength({ min: 5 })
], (req, res, next) => {
// weee
});
```
See #200
=> Version 4 - oneOf

check/check.js, check/one-of.js, filter/index.d.ts, filter/index.js, filter/matched-data.js, filter/matched-data.spec.js, filter/type-definition.spec.ts, test/mocha.opts, tsconfig.json
This is a follow-up of #383.
Adds a helper function to retrieve the subset of data validated in the current request, as requested in #168.
This can include only the valid data or all data (even invalid ones).
```js
const { check } = require('express-validator/check');
const { matchedData } = require('express-validator/filter');
app.post('/login', [
check('username').isEmail(),
check('password').isLength({ min: 5 })
], (req, res, next) => {
const data = matchedData(req);
// yay data should contain only { username, password } now
});
```
=> Version 4 - Get subset of validated data

README.md, check/type-definition.spec.ts, check/validation-result.js, check/validation-result.spec.js, lib/express_validator.js, shared-typings.d.ts, test/errorFormatter.spec.js, test/type-definition.spec.ts
Add to the Validation Result API a method `.formatWith(formatter)`.
Closes #392
=> check API - error formatter

README.md, check/check.js, check/check.spec.js, check/select-fields.js, check/select-fields.spec.js, check/type-definition.spec.ts, lib/express_validator.js, shared-typings.d.ts, test/check.spec.js, test/schema.spec.js, test/type-definition.spec.ts
Adds support for using validator sanitizers in the validation chain API.
Example:
```js
check('some.field').trim().escape().not().isEmpty();
```
Closes #417
=> Sanitizers in the validation chain API

README.md, check/check.js, filter/index.d.ts, filter/index.js, filter/sanitize-all.js, filter/sanitize-all.spec.js, filter/sanitize-body.js, filter/sanitize-body.spec.js, filter/sanitize-cookies.js, filter/sanitize-cookies.spec.js, filter/sanitize-params.js, filter/sanitize-params.spec.js, filter/sanitize-query.js, filter/sanitize-query.spec.js, filter/sanitize.js, filter/sanitize.spec.js, filter/type-definition.spec.ts, index.d.ts, shared-typings.d.ts, utils/constants.js
Follow up of #417/#418.
Adds standalone sanitization to the filter API:
```js
app.get('/', sanitize('email').normalizeEmail(), (req, res, next) => { ... });
```
=> Filter API - Standalone Sanitization

UPGRADE_GUIDE.md
The right attribute name is 'onlyFirstError' instead of 'firstErrorOnly'
=> Fix onlyFirstError attribute name on UPDATE-GUIDE

.editorconfig, README.md, check/index.d.ts, check/one-of.js, check/one-of.spec.js, check/type-definition.spec.ts
Adds support for passing groups of validations that must pass together to `oneOf()`:
```js
// This protected route must be accessed either by passing both username + password,
// or by passing an access token
app.post('/protected/route', oneOf([
[
check('username').exists(),
check('password').exists()
],
check('access_token').exists()
]), someRouteHandler);
```
Closes #434
=> oneOf() with subgroups of validations

README.md, filter/index.d.ts, filter/matched-data.js, filter/matched-data.spec.js, filter/type-definition.spec.ts
Implemented `locations` in matchedData to be able to get matched data from specified fields (like body, params...)
Closes #447
=> Implemented separated matched data for different locaitons

README.md, check/index.d.ts, check/type-definition.spec.ts, check/validation-result.d.ts, check/validation-result.js, check/validation-result.spec.js
This is a proposal to resolve https://github.com/ctavan/express-validator/issues/427, by introducing a way to set default options for the `validation-result` module
It introduces a new `.withDefaults` function, which will return a new instance of the module with specified default options. The decision to return a new instance was to avoid affecting the global module state in the case that multiple `validationResult` implementations are desired within the same application.
This is loosely inspired on the concept of `request.defaults` from the [request/request](https://github.com/request/request#requestdefaultsoptions) module
Here's a brief example:
```
// baseValidationResult.js ----
const { validationResult } = require('express-validator/check');
const result = …
```
=> check: support default options for validationResult

check/select-fields.js, check/select-fields.spec.js
this partially fixes the #458. as long as you specify where in the request to look for the field, instead of using the catch-call `check()` (ie, `param()`, `query()`, etc.), this fixes the issue.
it's only a partial fix, but it is a simple change and this at least makes it possible to do this kind of validation (ie checking for `undefined`'s)
=> fix issue where undefined nested properties under a wildcard are not validated

check/check.d.ts, check/check.spec.ts, check/one-of.d.ts, check/one-of.js, check/one-of.spec.js, check/one-of.spec.ts, check/runner.js, check/runner.spec.js, check/validation-chain-builders.d.ts, check/validation-chain-builders.spec.ts
Support validation messages that are functions, so to build them dynamically:
```js
check('foo', (value, { req, location, path }) => {})
.isEmail().withMessage((value, { req, location, path }) => {})
oneOf([ check('foo').isEmail() ], ({ req }) => {})
```
Closes #489, closes #466, closes #469
=> Dynamic messages

README.md
Small typo fix. The correct method name is `isUUID` according to `validator` package.
=> docs: method name typo at README.md

README.md, check/schema.d.ts, check/schema.spec.ts
This PR adds a Sanitizer schema when using the function `checkSchema`. 
Sanitizers like `toInt`, `escape` and so on now appears in the intellisense section and Typescript yields no more.
If something is missing please let me now.
=> Added SanitizersSchema

filter/matched-data.js, filter/matched-data.spec.js, utils/select-fields.js, utils/select-fields.spec.js
=> Avoid double sanitization when using matchedData()

check/runner.spec.js, utils/to-string.js
Fixes #431 
Highlights from https://github.com/ctavan/express-validator/issues/431#issuecomment-379474024:
> (...) this is an issue of toDate sanitizer combined with isISO8601 validator.
>
> All values are already being coerced into strings for the standard validators, 
with some special rules followed (...) I think Date objects should have a special rule as well.
=> Convert date to ISO string before validating it

utils/select-fields.js, utils/select-fields.spec.js
Wildcards may yield 0..* instances, each with a different path, so we may want to skip the filtering which was originally built for #331.
Fixes #531
Fixes #458
=> Don't filter values when selecting fields with wildcards

README.md, filter/matched-data.d.ts, filter/matched-data.js, filter/matched-data.spec.js, filter/matched-data.spec.ts, utils/select-fields.js, utils/select-fields.spec.js
Adds an option `includeOptionals` for this, otherwise it could be a breaking change.
Closes #568
=> Allow including optionals in return of matchedData

docs/feature-custom-validators-sanitizers.md
`id` is the name of the URL param being sanitized... but the variable in the function is named `value`.
=> Small correction to the sanitizer docs example

docs/feature-error-messages.md
`check().not().in()` results in: 
```
TypeError: check(...).not(...).in is not a function
```
Updated to be `check().not().isIn()` instead (see: https://express-validator.github.io/docs/validation-chain-api.html#not)
=> Update "Do not use a common word" example

docs/feature-schema-validation.md
I am using the schema validation and was looking for `nullable` solution. I found in the doc https://express-validator.github.io/docs/validation-chain-api.html that `optional` has the `nullable` option but I did not know it should be under `options`. It took me for a while to figure it out. So, I think updating this doc might help other people in future.
=> docs: show how to use optional options in the schema example

src/context-runners/sanitize.spec.ts, src/context-runners/sanitize.ts, src/context-runners/validate.spec.ts, src/context-runners/validate.ts, src/utils.ts
**This is a breaking change**
Now non-string values can finally be sanitized, woo!
Closes #641, closes #632, fixes #630, fixes #580, fixes #651
=> context-runners: sanitize non-string fields

docs/api-validation-chain.md
Fix typo `busines` => `business`.
=> docs: Fix typo

docs/api-validation-chain.md, src/chain/context-handler-impl.spec.ts, src/chain/context-handler-impl.ts, src/chain/context-handler.ts, src/context-items/bail.spec.ts, src/context-items/bail.ts
Supersedes #500
Stops validation if there's an error.
Logic for stopping validation reused from conditional validation, in #658.
=> Implement .bail()

src/middlewares/schema.spec.ts, src/middlewares/schema.ts
There's a bug in the typings when marking a field as optional.
For example, this flags as an error
```javascript
checkSchema({
foo: {
optional: {
options: {
nullable: true,
checkFalsy: true,
}
}
}
})
```
but allows the following:
```javascript
checkSchema({
foo: {
optional: {
nullable: true,
checkFalsy: true,
}
}
})
```
However, this has no effect.
This has been addressed previously in #693 but it looks like this has been regressed.
Also see #742
=> Fix typing for optional

src/chain/validators-impl.spec.ts, src/options.ts
This pull request updates the mobile phone locale by adding the `pt-BR' option, as the validator.js library already has this option for use.
Resolves #772
=> Update mobile phone locale options (#772)

src/base.ts
Accessing property in union of object types fails for properties not defined on all union members.
```
error TS2339: Property 'value' does not exist on type 'ValidationError'.
Property 'value' does not exist on type '{ location?: undefined; param: "_error"; msg: any; nestedErrors: ValidationError[]; }'.
```
Add optional types to all validation error fields for each union member. Fixes https://github.com/express-validator/express-validator/issues/795.
https://github.com/Microsoft/TypeScript/issues/12815
TypeScript v3.7.2
=> Fix error where property 'value' does not exist on type 'ValidationError’

src/utils.ts, tsconfig.json
It seems those features are all supported by Node 8, the minimal version supported by us.
It may even help fix #824.
=> Compile TS to ES2017

docs/feature-running-imperatively.md
I have added the example to run validators sequentially in the documentation.
This is related to https://github.com/express-validator/express-validator/issues/638#issuecomment-530999622
=> docs: Add example sequential processing of the validation chain

src/chain/sanitizers-impl.spec.ts, src/context-items/sanitization.spec.ts, src/context-items/sanitization.ts
I made this little tweak to make possible use customSanitize in async environments. I did not made a proper error handler because I don't know how to integrate that with the validators, so I don't think the work of this feature is done, that's just a draft. This is related to #784 
An example use case for this would be: ``body('user').customSanitizer(async(id) => await users.findById(id))``
Also made the tests for that
=> Made customSanitizer await for async functions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR adds issue and pull request templates. Templates give suggestions on what information need to be specified in a pull request or in an issue.
This closes #922
=> Add issue and pull request templates

package-lock.json, package.json
=> deps: bump validator to 13.5.2

src/options.ts
I was having issues with using a RegExp for the `ignore` property on `IsAlphaOptions`.
I'm using the latest version of **express-validator**:
```sh
╭─iamwillshepherd@ares ~/code/code-in-color/apli/server ‹applicants-need-love-too›
╰─$ cat package.json | grep "express-validator"
"express-validator": "^6.8.1",
```
I checked your `package.json` file and noticed y'all are depending on the latest release of `validator`.
https://github.com/express-validator/express-validator/blob/9b74459152fe0528eaacb79d473a942cb4b8e56a/package.json#L44-L47
If you head over to the test suite of validatorjs/validator, you'll notice that `isAlpha` accepts a `string` **or** `RegExp`
https://github.com/validatorjs/validator.js/blob/8831db31e7d5de03cb9744f811ffd256494f97f6/test/validators.js#L991-L1003 
So, I …
=> Fix: Updated IsAlphaOptions.ignore to allow string or RegExp

src/chain/validators-impl.spec.ts, src/chain/validators-impl.ts, src/options.ts
This addresses a type bug introduced in #952.
https://github.com/express-validator/express-validator/pull/963#issuecomment-752722295
=> fix(IsAlphaOptions.ignore): convert 'string[]' to 'string'

src/utils.spec.ts, src/utils.ts
https://github.com/express-validator/express-validator/issues/791#issuecomment-752924430
```js
const value = {
toString: 'something',
};
// returns '[object Object]' instead of throwing
const v = toString(value)
```
=> fix(toString): no longer throwing with custom Object.toString

docs/api-check.md, docs/feature-running-imperatively.md, src/middlewares/schema.spec.ts, src/middlewares/schema.ts
=> feat(checkSchema): run imperatively

docs/api-validation-chain.md, src/chain/validators-impl.spec.ts, src/chain/validators-impl.ts, src/chain/validators.ts
This PR implements `isObject` validator to validate objects.
`strict` option defaults to `true` so that arrays and null values does not pass validation, but it can be marked as `false` to allow them.
Closes #882
=> feat: add 'isObject' validator

package-lock.json, package.json
Fixes #1003 
Bump lodash version from 4.17.20 to 4.17.21
=> fix(security): Bump lodash version to 4.17.21

src/base.ts
We change the context key from  a `string` type, which does not guarantee unicity, to a [`Symbol`](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Symbol).
=> chore: document why not using `Symbol` for `contextsKey`

docs/api-validation-chain.md, src/context-items/custom-condition.spec.ts
Closes #1028 
Changing this behaviour should be as simple as moving the await on the previous line, but would become a breaking change and I am not 100% sure if it would make sense.
=> docs: warn users about returning `falsy` values in `.if()` with async condition

docs/api-check.md, src/chain/context-runner-impl.ts, src/middlewares/one-of.spec.ts, src/middlewares/one-of.ts
Fixes #995 
~~Note that the ResultWithContext of a `ValidationChain` and `oneOf` is slightly different.~~ 
```js
// body('foo').isString().run({ req: { foo: 'foo' } })
ResultWithContext {
formatter: [Function (anonymous)],
errors: [
{
value: 'foo',
msg: 'Invalid value',
param: 'foo',
location: 'body'
}
],
context: Context {
fields: [ 'foo' ],
locations: [ 'body' ],
stack: [ [StandardValidation] ],
optional: false,
message: undefined,
_errors: [ [Object] ],
dataMap: Map(1) { 'body:foo' => [Object] }
}
}
// oneOf([body('foo').isString()]).run({ req: { foo: 'foo' } })
ResultWithContext {
formatter: [Function (anonymous)],
errors: [
{ msg: 'Invalid value(s)', param: '_error', nestedErrors: [Array] }
],
context: Context {
fields: [],
locations: [],
stack: [ [Object] ],
optional: false, …
```
=> fix(oneOf): return `Result` when running imperatively

package.json
Closes #1034 
This PR can be tested running `npm publish --dry-run` with `npm@7` installed.
=> npm: correctly exclude `.ts` files when publishing with `npm@7`

docs/feature-error-messages.md, src/context-items/custom-validation.spec.ts, src/context-items/custom-validation.ts
Fixes #1047.
- Adjusted tests to account for set validation messages overriding thrown errors.
- They were split into two `describe` blocks, one with and one without a message set.
- Adjusted `src/context-items/custom-validation.ts` to favor the set message over the thrown message.
- Tweaks "Custom Validator Level" section of `docs/feature-error-messages.md` to clarify this overriding behavior.
=> fix: prioritize `withMessage` errors over the ones thrown by `CustomValidator`

docs/api-check.md, jest.config.js, src/middlewares/__snapshots__/one-of.spec.ts.snap, src/middlewares/one-of.spec.ts, src/middlewares/one-of.ts
This closes #956 
We allow the user to choose between different error types:
- `grouped`: new default behaviour that groups the errors based on the original branches.
- `legacy`: old behaviour that joins  the errors from different branches together
- `leastErroredOnly`: returns only the group with less errors
=> feat(oneOf): add new error types

src/middlewares/schema.ts
When getting a list of result by calling `checkSchema().run`, I was unable to use those handy methods on result as it was marked as `unknown` currently. 
Would be def great if we could add type support for the return of `checkSchema`, thanks.
Type definition for `checkSchema` function return.
=> fix: add type for `checkSchema` function return

docs/feature-custom-validators-sanitizers.md
Fixes #1087 
https://express-validator.github.io/docs/custom-validators-sanitizers.html
The above documentation promotes a couple of bad practices that might affect the quality of the documentation.
- Illustration of accessing data layer directly from validation layer
- Promoting the usage of unvalidated data
=> docs: warn users about bad practice

docs/feature-schema-validation.md
Current schema validation usage according to [the feature example](https://express-validator.github.io/docs/schema-validation.html) of `isPostalCode` results in an error: 
```json
"errors": {
"message": "Invalid locale 'undefined'"
}
```
According to #1085, a PR for v7 is on the way to improve this (?). Anyway, I'd appreciate it if you could update this in the documentation of v6 as well. Do tell me if I should PR to a different branch (`v6.13-features` maybe?) instead.
=> schema usage according to documentation results in Error

docs/feature-schema-validation.md
Missing `validationResult()` usage could make someone hard to use express-validator with Schema Validation at the beginning so it would be better to add little more codes.
=> Add `validationResult()` for schema validation example

src/chain/validators-impl.spec.ts, src/chain/validators-impl.ts
Forcing pattern to be string, to cope with lib validator which doesn't reset the RegExp instance
Fixes https://github.com/express-validator/express-validator/issues/1127
Workaround of a behaviour which should be fixed in validator.js
=> fix: correctly run .matches when passing regex object

docs/api-sanitization-chain.md
fixed typo in line 115, changed 'bar to 'bar'
=> docs: update sanitization chain

.github/workflows/ci.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> gh: upgrade checkout and setup-node actions

src/chain/context-runner-impl.spec.ts, src/context-items/bail.spec.ts, src/context-items/custom-validation.spec.ts, src/context-items/custom-validation.ts, src/context-items/standard-validation.spec.ts, src/context-items/standard-validation.ts, src/context.spec.ts, src/context.ts, src/middlewares/one-of.ts
I'm changing the signature of `Context#addError()` because using method overloads was a mistake 😛 
Discriminated unions work much better as the intent becomes clear for the consumer code.
Furthermore, I'm planning on adding yet another style of error for v7, so the overloads would become even more confusing going forward...
=> Change signature of Context#addError()

src/express-validator.spec.ts, src/express-validator.ts, src/index.ts, src/middlewares/schema.ts
This adds the `ExpressValidator` class, which can hold extension validators, sanitisers and default result formatters.
It can be used like this:
```js
const { check, body, checkSchema, validationResult } = new ExpressValidator(
// Custom validators
{ isAllowedDomain: value => { ... } },
// Custom sanitizers
{ removeDomain: value => { ... } },
// Options. Currently only errorFormatter
{ errorFormatter: error => `Error of type ${error.type}` },
);
app.post('/new-user', [
check('email')
.trim()
.isEmail()
.isAllowedDomain()
.removeDomain()
], (req, res) => {
console.log(validationResult(req).array());
// => 'Error of type field'
});
```
=> Add ExpressValidator class

src/field-selection.spec.ts, src/field-selection.ts
In a nutshell, any field paths with `**` will now be considered a wildcard that can deeply match fields.
For example:
| Input path | Input object | Selected fields |
| ---------- | ------------ | --------------- |
| `**` | `{ a: { foo: 1, bar: 2 }, b: { c: { d: { e: 3 } } } }` | `a.foo`, `a.bar`, `b.c.d.e` |
| `**.foo` | `{ a: { foo: 1, bar: 2 }, b: { c: { foo: 3 } }, foo: 4 }` | `a.foo`, `b.c.foo`, `foo` |
Works with both `check()` + variants, and `checkExact()`.
I'm pretty sure that some issue here on GitHub asked for this feature but I can't find them to link them here.
=> Add globstar (wildcard deep matching) support

src/chain/context-handler-impl.spec.ts, src/chain/context-handler-impl.ts, src/chain/context-handler.ts, src/chain/context-runner-impl.spec.ts, src/chain/context-runner-impl.ts, src/chain/context-runner.ts, src/chain/validation-chain.ts, src/context-builder.spec.ts, src/context-builder.ts, src/context.ts, src/middlewares/exact.ts, src/middlewares/one-of.spec.ts, src/middlewares/one-of.ts, src/middlewares/schema.spec.ts, src/middlewares/schema.ts, src/utils.ts
Closes #1100
Implements an option to `.bail()` so that no further contexts will run if there are any errors.
Supports:
⚠️ This is a perf-loss for those using any of the above functions, as the chains now need to be awaited on, otherwise results will be unreliable.
Suppose that you have a request with 1k fields, one validator on each field, each taking 10ms to complete.
Also suppose that no fields present errors, so every validator runs.
On my machine, the time it takes for running all validation chains looks like this:
- **With request-level bail on every field:** 10s
- **With request-level bail on half of all fields:** 10s (no difference)
- **With request-level bail on a third of all fields:** ~7s (roughly 1/3 better than the above scenarios)
- **Without request-level bail:** ~100 ms.
=> Request-level bail

docs/guides/manually-running.md
A small change in the example to use `const` because the variable is not reassigned
=> docs: prefer `const` over `let`

docs/migration-v6-to-v7.md
Small typo in the Documentation for the change from `ValidationSchema` to `Schema`
Found a typo while reading the documentation. Small fix describing the upgrade form 6 to 7 and the remove of `ValidationSchema`
=> Typo of ValidationSchema

docs/api/matched-data.md, docs/api/misc.md, src/matched-data.ts
As brought up in https://github.com/express-validator/express-validator/issues/1041, it's currently _hard_ to type the result of `parsedData`. It comes with all fields set as `any` unless we do a [type assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) via the `as` keyword.
```ts
const { something } = parsedData(req);
// something has any type
const { something } = parsedData(req) as { something: string };
// something has string type
```
However, this syntax _overrides_ all type-checking. To mitigate that, this PR adds an optional [generic type](https://www.typescriptlang.org/docs/handbook/2/generics.html) to the `parsedData` function signature, so it becomes:
```ts
function matchedData<T = Record<string, any>>(
req: Request,
options: …
```
=> feat(matchedData): add generic types for return

package-lock.json, package.json
We actively maintain this library and implement new features swiftly when they get released from [validatorjs](https://github.com/validatorjs/validator.js). 
#1251 is likely being cause by a new validatorjs minor version introducing a breaking change by mistake. To prevent this we can pin the library version to patch and manually update the entry when required.
=> fix: pin validator version to patch

docs/guides/manually-running.md, website/versioned_docs/version-7.0.0/guides/manually-running.md
The "manually running" guide's typescript example should use `ContextRunner` instead of `ValidationChain` as it is a more minimal interface required by the example helper.
=> docs(guide/manually-running) typescript example should use `ContextRunner`

docs/guides/manually-running.md
The errors property of the Result<T> class in validation-result.ts is not accessible because it is a private property.
- I thought about opening the errors property as public, but I didn't think it was a good way to encapsulate it
=> docs: typescript example should use isEmpty method (guide/manually-running)

docs/guides/field-selection.md
There is a missing preposition on line 120 of the `field-selection` page of the docs which I have added. Found this while reading the docs.
This pull request is ready to merge.
=> docs: add preposition

src/options.ts
I have added some props into IsURLOptions interface that may be needed in the function isFQDN()
Relevant issue:
Closes https://github.com/express-validator/express-validator/issues/1258
- [-] I have added tests for what I changed.
=> #1258: added some props into IsURLOptions interface

docs/api/validation-chain.md, src/base.ts, src/chain/context-runner-impl.spec.ts, src/chain/context-runner-impl.ts, src/chain/sanitizers-impl.spec.ts, src/chain/validators-impl.spec.ts, src/context-items/bail.spec.ts, src/context-items/chain-condition.spec.ts, src/context-items/custom-condition.spec.ts, src/context-items/custom-validation.spec.ts, src/context-items/sanitization.spec.ts, src/context-items/standard-validation.spec.ts, src/context.spec.ts, src/express-validator.spec.ts, src/field-selection.spec.ts, src/field-selection.ts
Adds `pathValues` to the `Meta` interface, used by `custom()` and `customSanitizer()`.
It's an array of values that come from wildcards or globstars.
Closes #1297
=> Add wildcard values to custom validator's metadata

src/express-validator.spec.ts, src/field-selection.spec.ts, src/field-selection.ts
Fixes #1245 
It is correct to assume that primitives will not have properties in a request.
Despite that express-validator should provide the correct result, so if a user wants to validate a non existent property we should treat that as undefined.
Eventually in the future we may also update `FieldInstance` to look something like this:
```typescript
export interface FieldInstance {
path: string;
originalPath: string;
location: Location;
value: any;
exists: boolean // added property
}
```
=> fix: correctly select properties of primitives

src/field-selection.ts
use forEach instead of map because the return value is not used
=> refactor: use "forEach" instead of "map"
